vim.pack.add({ "https://github.com/windwp/nvim-autopairs" })
require("nvim-autopairs").setup()
vim.pack.add({ "https://github.com/numToStr/Comment.nvim" })
require("Comment").setup()
vim.keymap.set('n', '<C-_>', function() require('Comment.api').toggle.linewise.current() end, { noremap = true, silent = true })
vim.keymap.set('v', '<C-_>', function() require('Comment.api').toggle.linewise(vim.fn.visualmode()) end, { noremap = true, silent = true })
vim.pack.add({ "https://github.com/nvim-lua/plenary.nvim" })
vim.pack.add({ "https://github.com/folke/todo-comments.nvim" })
require("todo-comments").setup({})
vim.pack.add({ "https://github.com/laytan/cloak.nvim" })
require('cloak').setup({ enabled = true, cloak_character = '*', highlight_group = 'Comment', try_all_patterns = true, cloak_telescope = true, cloak_on_leave = false, patterns = { { file_pattern = '.env*', cloak_pattern = '=.+', replace = nil } } })
vim.pack.add({ "https://github.com/windwp/nvim-ts-autotag" })
require("nvim-ts-autotag").setup()
